name: Deploy to Render

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK_URL }}